### ISSUE TITLE
Podcast RSS

### ISSUE THREAD

**Issue by iBobik** [meloncholy/mixcloud-rss#1]
Could you add audio files to the RSS feed to allow podcasts downloaders (like iTunes, iCatcher, ...) to download recordings?

**Comment by meloncholy** [comment]
No, I'm afraid I can't. The MixCloud to RSS converter uses MixCloud’s embeds, which are little Flash apps. It’s not possible to get the audio stream directly as MixCloud doesn’t supply it. 

I know this rather limits their usefulness; you could email the guys at MixCloud about this, but (for the reasons [they give here](http://www.mixcloud.com/developers/documentation/#audio-streams)) it’s unlikely they’ll change their minds.

I wish I could fix this as you're not the first person to ask about it, but I can't. Sorry!

**Comment by monpac** [comment]
They aren't necesarrily Flash anymore as they have added Html5 to their embeded objects. Would their be any way of extracting that audio now for podcasts players to download?

Pages like Offliberty.com can download mixcloud podcasts, although I can't think of a way to do all this process automatically. Sorry for bothering though.

**Comment by meloncholy** [comment]
Ooh, you're right! Thanks for pointing that out. Though it still uses a Flash app to play the audio (this seems to be the way to go right now -- SoundCloud does the same thing). I'm currently updating this project to make it shinier (Bootstrap 3, Backbone, Dust, caching of feeds), so I'll definitely see if I can use the new iframe embeds. 

The main issue here is not so much that it's impossible to get the audio stream directly (despite, um, what I said in my comment above :) -- like most sites, Mixcloud uses HTTP streaming and I don't think I'm revealing any big secrets by saying it's pretty easy to get the audio via DevTools -- but more that I don't want to piss off the guys at Mixcloud and get my site blocked. I'd love them to offer a download option, but until they do I can't really do so either. Sorry.
