### ISSUE TITLE
Enclosures?

### ISSUE THREAD

**Issue by jeckman** [meloncholy/mixcloud-rss#2]
Is it possible to get access to an enclosure via the Mixcloud API to download a source MP3 file?

If you sync podcasts to a device using this, the oembed version isn't enough

**Comment by meloncholy** [comment]
As I said in #1, Mixcloud doesn't allow this unfortunately and it's not something I want to hack around as I don't want my site blocked. I know it limits what you can do with them quite severely (syncing podcasts, using with iTunes, etc.). Sorry and wish I had better news. :/

**Comment by jeckman** [comment]
Thanks - understood.
